# It represents actual storage available in the cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data1
---
# PersistentVolumeClaim (namespace-scoped)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: my-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# Pod using PVC
apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: my-ns
spec:
  volumes:
    - name: mypvc1
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: "/mnt/data"
          name: mypvc1