# Use the official Nginx image as the base image
FROM nginx:mainline-alpine3.23-perl
# Copy the index.html file to the default Nginx HTML directory
COPY index.html /usr/share/nginx/html/index.html
# Expose port 80 to the outside world
EXPOSE 80